
import { ProfessionalProfile, BookingStatus, Booking, User, Role } from './types';

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Zayan Mallick', email: 'zayan@example.com', role: Role.USER, isVerified: true, avatar: 'https://i.pravatar.cc/150?u=u1' },
  { id: 'u2', name: 'Farhan Ahmed', email: 'farhan@pro.com', role: Role.PROFESSIONAL, isVerified: true, avatar: 'https://i.pravatar.cc/150?u=u2' },
  { id: 'u3', name: 'Tania Kabir', email: 'tania@pro.com', role: Role.PROFESSIONAL, isVerified: true, avatar: 'https://i.pravatar.cc/150?u=u3' },
  { id: 'u4', name: 'Sameer Rahman', email: 'sameer@pro.com', role: Role.PROFESSIONAL, isVerified: true, avatar: 'https://i.pravatar.cc/150?u=u4' },
  { id: 'u5', name: 'Nusrat Jahan', email: 'nusrat@pro.com', role: Role.PROFESSIONAL, isVerified: true, avatar: 'https://i.pravatar.cc/150?u=u5' },
  { id: 'u100', name: 'Admin One', email: 'admin@probd.com', role: Role.ADMIN, isVerified: true, avatar: 'https://i.pravatar.cc/150?u=u100' },
  { id: 'u200', name: 'Mod Sarah', email: 'sarah@probd.com', role: Role.MODERATOR, isVerified: true, avatar: 'https://i.pravatar.cc/150?u=u200' },
];

export const MOCK_PROFESSIONALS: ProfessionalProfile[] = [
  {
    id: 'p1',
    userId: 'u2',
    name: 'Adv. Farhan Ahmed',
    avatar: 'https://picsum.photos/200/200?random=1',
    category: 'Legal',
    specialties: ['Corporate Law', 'IP Rights', 'Dispute Resolution'],
    rates: 5000,
    experience: 12,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Senior consultant specializing in Bangladeshi corporate regulations and international trade laws.',
    rating: 4.9,
    reviewCount: 128,
    status: 'Available Now'
  },
  {
    id: 'p2',
    userId: 'u3',
    name: 'Tania Kabir, FCA',
    avatar: 'https://picsum.photos/200/200?random=2',
    category: 'Financial',
    specialties: ['Strategic Tax Planning', 'Audit', 'Financial Advisory'],
    rates: 3500,
    experience: 8,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Expert chartered accountant with a focus on startup taxation and financial compliance.',
    rating: 4.8,
    reviewCount: 94,
    status: 'Busy'
  },
  {
    id: 'p3',
    userId: 'u4',
    name: 'Dr. Sameer Rahman',
    avatar: 'https://picsum.photos/200/200?random=3',
    category: 'Medical',
    specialties: ['Mental Health', 'Clinical Psychology', 'Family Therapy'],
    rates: 2500,
    experience: 15,
    languages: ['Bengali', 'English', 'Hindi'],
    isVerified: true,
    isApproved: true,
    bio: 'Compassionate psychologist dedicated to mental well-being and family counseling.',
    rating: 5.0,
    reviewCount: 215,
    status: 'Offline'
  },
  {
    id: 'p4',
    userId: 'u5',
    name: 'Dr. Nusrat Jahan',
    avatar: 'https://picsum.photos/200/200?random=4',
    category: 'Medical',
    specialties: ['Pediatrics', 'Child Nutrition', 'Neonatology'],
    rates: 2000,
    experience: 10,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Specialist in child health and development with over a decade of experience in leading hospitals.',
    rating: 4.9,
    reviewCount: 86,
    status: 'Available Now'
  },
  {
    id: 'p5',
    userId: 'u6',
    name: 'Adv. S.M. Zaki',
    avatar: 'https://picsum.photos/200/200?random=5',
    category: 'Legal',
    specialties: ['Criminal Defense', 'Human Rights', 'Litigation'],
    rates: 6000,
    experience: 20,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Renowned criminal defense attorney known for handling high-profile cases in the High Court.',
    rating: 4.7,
    reviewCount: 156,
    status: 'Busy'
  },
  {
    id: 'p6',
    userId: 'u7',
    name: 'Rafiqul Islam, CPA',
    avatar: 'https://picsum.photos/200/200?random=6',
    category: 'Financial',
    specialties: ['Corporate Tax', 'Forensic Audit', 'Risk Management'],
    rates: 4000,
    experience: 11,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Expert in corporate risk mitigation and forensic accounting for multinational corporations.',
    rating: 4.6,
    reviewCount: 72,
    status: 'Offline'
  },
  {
    id: 'p7',
    userId: 'u8',
    name: 'Dr. Anisur Rahman',
    avatar: 'https://picsum.photos/200/200?random=7',
    category: 'Medical',
    specialties: ['Cardiology', 'Internal Medicine', 'Hypertension'],
    rates: 3000,
    experience: 18,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Leading cardiologist specializing in non-invasive heart procedures and chronic disease management.',
    rating: 5.0,
    reviewCount: 312,
    status: 'Available Now'
  },
  {
    id: 'p8',
    userId: 'u9',
    name: 'Adv. Mehnaz Chowdhury',
    avatar: 'https://picsum.photos/200/200?random=8',
    category: 'Legal',
    specialties: ['Family Law', 'Divorce & Mediation', 'Child Custody'],
    rates: 3500,
    experience: 7,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Dedicated family lawyer focused on achieving amicable settlements through expert mediation.',
    rating: 4.8,
    reviewCount: 64,
    status: 'Available Now'
  },
  {
    id: 'p9',
    userId: 'u10',
    name: 'Sumaiya Akter',
    avatar: 'https://picsum.photos/200/200?random=9',
    category: 'Medical',
    specialties: ['Nutritionist', 'Diet Planning', 'Diabetes Care'],
    rates: 1500,
    experience: 5,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Certified dietitian helping clients achieve wellness through personalized nutrition and lifestyle changes.',
    rating: 4.5,
    reviewCount: 42,
    status: 'Available Now'
  },
  {
    id: 'p10',
    userId: 'u11',
    name: 'Mahbubul Alam',
    avatar: 'https://picsum.photos/200/200?random=10',
    category: 'Financial',
    specialties: ['Investment Advisory', 'Wealth Management', 'IPO'],
    rates: 7000,
    experience: 14,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Financial strategist assisting high-net-worth individuals and firms with portfolio diversification.',
    rating: 4.7,
    reviewCount: 89,
    status: 'Busy'
  },
  {
    id: 'p11',
    userId: 'u12',
    name: 'Dr. Rubaiya Khan',
    avatar: 'https://picsum.photos/200/200?random=11',
    category: 'Medical',
    specialties: ['Dermatology', 'Aesthetics', 'Skin Care'],
    rates: 2500,
    experience: 9,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Consultant dermatologist focused on therapeutic skin treatments and modern aesthetic procedures.',
    rating: 4.9,
    reviewCount: 112,
    status: 'Offline'
  },
  {
    id: 'p12',
    userId: 'u13',
    name: 'Adv. Kamal Uddin',
    avatar: 'https://picsum.photos/200/200?random=12',
    category: 'Legal',
    specialties: ['Property Law', 'Real Estate', 'Vetting'],
    rates: 4500,
    experience: 15,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Expert in real estate documentation and property dispute resolution in the Bangladesh market.',
    rating: 4.6,
    reviewCount: 78,
    status: 'Available Now'
  },
  {
    id: 'p13',
    userId: 'u14',
    name: 'Zeeshan Haider',
    avatar: 'https://picsum.photos/200/200?random=13',
    category: 'Tech',
    specialties: ['FinTech Consultant', 'Blockchain', 'Digital Banking'],
    rates: 8000,
    experience: 6,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Technology consultant helping banks and fintech startups navigate the digital transformation landscape.',
    rating: 4.8,
    reviewCount: 34,
    status: 'Busy'
  },
  {
    id: 'p14',
    userId: 'u15',
    name: 'Dr. Iftekhar Mahmud',
    avatar: 'https://picsum.photos/200/200?random=14',
    category: 'Medical',
    specialties: ['Psychiatry', 'Neuropsychiatry', 'Addiction'],
    rates: 3000,
    experience: 13,
    languages: ['Bengali', 'English'],
    isVerified: true,
    isApproved: true,
    bio: 'Psychiatrist specializing in complex neurological conditions and addiction recovery programs.',
    rating: 4.9,
    reviewCount: 97,
    status: 'Available Now'
  }
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    userId: 'u1',
    userName: 'Zayan Mallick',
    professionalId: 'p1',
    professionalName: 'Adv. Farhan Ahmed',
    startTime: new Date(Date.now() + 3600000).toISOString(),
    endTime: new Date(Date.now() + 7200000).toISOString(),
    status: BookingStatus.CONFIRMED,
    price: 5000
  },
  {
    id: 'b2',
    userId: 'u1',
    userName: 'Zayan Mallick',
    professionalId: 'p2',
    professionalName: 'Tania Kabir, FCA',
    startTime: new Date(Date.now() - 86400000).toISOString(),
    endTime: new Date(Date.now() - 82800000).toISOString(),
    status: BookingStatus.COMPLETED,
    price: 3500,
    notes: 'Discussed Q3 tax filing and VAT exemptions.',
    review: {
      id: 'r1',
      rating: 5,
      comment: 'Excellent financial advice! Tania is very professional and knowledgeable about local tax laws.',
      createdAt: new Date(Date.now() - 80000000).toISOString()
    }
  },
  {
    id: 'b3',
    userId: 'u5',
    userName: 'Unknown Client',
    professionalId: 'p1',
    professionalName: 'Adv. Farhan Ahmed',
    startTime: new Date(Date.now() - 172800000).toISOString(),
    endTime: new Date(Date.now() - 169200000).toISOString(),
    status: BookingStatus.CANCELLED,
    price: 5000
  }
];
